import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GTM_ID } from "@/lib/gtm";
import { Suspense } from "react";
import Analytics from "@/components/Analytics";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <meta id={GTM_ID} />
      <body>
        <Suspense>
          <Analytics />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
